<?xml version="1.0" encoding="utf-8"?><Database Name="BDLibros" Class="LibrosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-4ISN3C7S;Initial Catalog=BDLibros;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BDLibrosConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TCliente" Member="Cliente">
    <Type Name="Cliente">
      <Column Name="CodCliente" Type="System.String" DbType="VarChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Apellidos" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Nombres" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Cliente_Detalle" Member="Detalle" ThisKey="CodCliente" OtherKey="CodCliente" Type="Detalle" />
    </Type>
  </Table>
  <Table Name="dbo.TDetalle" Member="Detalle">
    <Type Name="Detalle">
      <Column Name="NroPedido" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CodLibro" Type="System.String" DbType="VarChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CodCliente" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrecioUnitario" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Association Name="Cliente_Detalle" Member="Cliente" ThisKey="CodCliente" OtherKey="CodCliente" Type="Cliente" IsForeignKey="true" />
      <Association Name="Libro_Detalle" Member="Libro" ThisKey="CodLibro" OtherKey="CodLibro" Type="Libro" IsForeignKey="true" />
      <Association Name="Pedido_Detalle" Member="Pedido" ThisKey="NroPedido" OtherKey="NroPedido" Type="Pedido" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TLibro" Member="Libro">
    <Type Name="Libro">
      <Column Name="CodLibro" Type="System.String" DbType="VarChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Titulo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Autor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Genero" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Resumen" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="Stock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Libro_Detalle" Member="Detalle" ThisKey="CodLibro" OtherKey="CodLibro" Type="Detalle" />
    </Type>
  </Table>
  <Table Name="dbo.TPedido" Member="Pedido">
    <Type Name="Pedido">
      <Column Name="NroPedido" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Anulado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Pedido_Detalle" Member="Detalle" ThisKey="NroPedido" OtherKey="NroPedido" Type="Detalle" />
    </Type>
  </Table>
  <Table Name="dbo.TUsuario" Member="Usuario">
    <Type Name="Usuario">
      <Column Name="CodUsuario" Type="System.String" DbType="VarChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NomUsuario" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Contrasena" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.spLoginUsuarioE" Method="spLoginUsuarioE">
    <Parameter Name="NomUsuario" Parameter="nomUsuario" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Contrasena" Parameter="contrasena" Type="System.String" DbType="VarChar(30)" />
    <ElementType Name="spLoginUsuarioEResult">
      <Column Name="CodError" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mensaje" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spActualizarLibro" Method="spActualizarLibro">
    <Parameter Name="CodLibro" Parameter="codLibro" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Titulo" Parameter="titulo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Autor" Parameter="autor" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Genero" Parameter="genero" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Resumen" Parameter="resumen" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Precio" Parameter="precio" Type="System.Decimal" DbType="Decimal(4,2)" />
    <Parameter Name="Stock" Parameter="stock" Type="System.Int32" DbType="Int" />
    <ElementType Name="spActualizarLibroResult">
      <Column Name="CodError" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mensaje" Type="System.String" DbType="VarChar(17) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spEliminarLibro" Method="spEliminarLibro">
    <Parameter Name="CodLibro" Parameter="codLibro" Type="System.String" DbType="VarChar(4)" />
    <ElementType Name="spEliminarLibroResult">
      <Column Name="CodError" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mensaje" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spListarLibro" Method="spListarLibro">
    <ElementType Name="spListarLibroResult">
      <Column Name="CodLibro" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="Titulo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Autor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Genero" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Resumen" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="Stock" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spActualizarCliente" Method="spActualizarCliente">
    <Parameter Name="CodCliente" Parameter="codCliente" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Apellidos" Parameter="apellidos" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Nombres" Parameter="nombres" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="spActualizarClienteResult">
      <Column Name="CodError" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mensaje" Type="System.String" DbType="VarChar(19) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spEliminarCliente" Method="spEliminarCliente">
    <Parameter Name="CodCliente" Parameter="codCliente" Type="System.String" DbType="VarChar(4)" />
    <ElementType Name="spEliminarClienteResult">
      <Column Name="CodError" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mensaje" Type="System.String" DbType="VarChar(27) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spListarClientes" Method="spListarClientes">
    <ElementType Name="spListarClientesResult">
      <Column Name="CodCliente" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="Apellidos" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Nombres" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spAgregarLibro" Method="spAgregarLibro">
    <Parameter Name="Titulo" Parameter="titulo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Autor" Parameter="autor" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Genero" Parameter="genero" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Resumen" Parameter="resumen" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Precio" Parameter="precio" Type="System.Decimal" DbType="Decimal(4,2)" />
    <Parameter Name="Stock" Parameter="stock" Type="System.Int32" DbType="Int" />
    <ElementType Name="spAgregarLibroResult">
      <Column Name="CodError" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mensaje" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spAgregarCliente" Method="spAgregarCliente">
    <Parameter Name="Apellidos" Parameter="apellidos" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Nombres" Parameter="nombres" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="spAgregarClienteResult">
      <Column Name="CodError" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mensaje" Type="System.String" DbType="VarChar(17) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spBuscarCliente" Method="spBuscarCliente">
    <Parameter Name="variable" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="spBuscarClienteResult">
      <Column Name="CodCliente" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="Apellidos" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Nombres" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spBuscarLibro" Method="spBuscarLibro">
    <Parameter Name="variable" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="spBuscarLibroResult">
      <Column Name="CodLibro" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="Titulo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Autor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Genero" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Resumen" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="Stock" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spRealizarVenta" Method="spRealizarVenta">
    <Parameter Name="CodCliente" Parameter="codCliente" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="CodLibro" Parameter="codLibro" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Int32" DbType="Int" />
    <ElementType Name="spRealizarVentaResult">
      <Column Name="CodError" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mensaje" Type="System.String" DbType="VarChar(33) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spListarVentas" Method="spListarVentas">
    <ElementType Name="spListarVentasResult">
      <Column Name="NroPedido" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="CodCliente" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="CodLibro" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="Nombres" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Apellidos" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Titulo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>